### ISSUE TITLE
Some UnsupportedOperation Exceptions after latest image updates

### ISSUE THREAD

**Issue by icraggs-sparkplug** [eclipse/sparkplug#321]
I'm getting some of the following exceptions while building after the latest image updates: 

     java.lang.UnsupportedOperationException: class net.sourceforge.plantuml.sequencediagram.teoz.NotesTile
        at net.sourceforge.plantuml.sequencediagram.teoz.AbstractTile.getYPoint(AbstractTile.java:40)
        at net.sourceforge.plantuml.sequencediagram.teoz.TileParallel.getYPoint(TileParallel.java:83)
        at net.sourceforge.plantuml.sequencediagram.teoz.TileParallel.getPreferredHeight(TileParallel.java:97)
        at net.sourceforge.plantuml.sequencediagram.teoz.GroupingTile.fillPositionelTiles(GroupingTile.java:230)
        at net.sourceforge.plantuml.sequencediagram.teoz.PlayingSpace.drawUInternal(PlayingSpace.java:109)
        at net.sourceforge.plantuml.sequencediagram.teoz.PlayingSpace.getPreferredHeight(PlayingSpace.java:134)
        at net.sourceforge.plantuml.sequencediagram.teoz.PlayingSpaceWithParticipants.calculateDimension(PlayingSpaceWithParticipants.java:71)
        at net.sourceforge.plantuml.sequencediagram.teoz.SequenceDiagramFileMakerTeoz.<init>(SequenceDiagramFileMakerTeoz.java:99)
        at net.sourceforge.plantuml.sequencediagram.SequenceDiagram.getSequenceDiagramPngMaker(SequenceDiagram.java:234)
        at net.sourceforge.plantuml.sequencediagram.SequenceDiagram.getNbImages(SequenceDiagram.java:412)
        at org.asciidoctor.diagram.plantuml.PlantUML.generate(PlantUML.java:125)

Is anyone else or just me? @fdesbiens

**Comment by wes-johnson** [comment]
Did you do a new pull - I submitted a fix for that here: https://github.com/eclipse/sparkplug/pull/320/commits/87fd8c680137a9d6ef198457dc8a48994cef86ee#diff-a5707a60081fea7c7e704a4ff9ec3ffcd5f581de610854c975f507437fd8d7e8

There was a typo (extra /) in the puml file. Once I cleaned that up I was able to build.

**Comment by icraggs-sparkplug** [comment]
Yes it works now, thanks.
